import { Link } from 'react-router-dom';
import { FileText, ChevronLeft } from 'lucide-react';

export default function TermsConditionsPage() {
  return (
    <div className="bg-slate-50 min-h-[calc(100vh-5rem)] py-16 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto">
        <Link to="/" className="inline-flex items-center text-orange-600 hover:text-orange-700 font-semibold text-sm mb-8 transition gap-1">
          <ChevronLeft className="w-4 h-4" /> Back to Home
        </Link>

        <div className="bg-white rounded-3xl p-8 md:p-12 shadow-sm border border-slate-100">
          <div className="flex items-center gap-4 mb-6">
            <div className="p-3 bg-orange-50 rounded-2xl text-orange-500">
              <FileText className="w-8 h-8" />
            </div>
            <div>
              <h1 className="text-3xl font-extrabold text-slate-900 tracking-tight">Terms & Conditions</h1>
              <p className="text-sm text-slate-500 mt-1">Last Updated: May 2026</p>
            </div>
          </div>

          <div className="prose prose-slate max-w-none space-y-6 text-slate-600 leading-relaxed">
            <div className="p-4 bg-amber-50 border border-amber-200 rounded-2xl text-amber-800 text-sm">
              <strong>Practice Purpose Only:</strong> These terms declare that Resume Analysis is a developer training application and is not intended for commercial employment assistance or standard business operations.
            </div>

            <section>
              <h2 className="text-xl font-bold text-slate-900 mb-2">1. Acceptance of Terms</h2>
              <p>
                By accessing this personal project sandbox, you acknowledge that it has been created purely for coding practice by <strong>Yannam Bhargavi</strong>. It is provided "as-is" without any warranties of service uptime, data longevity, or analytical accuracy.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-slate-900 mb-2">2. Educational Sourcing Disclaimer</h2>
              <p>
                Some assets, layouts, and tutorial code implementations were adapted from public learning resources and examples on the web. This code is modified and presented strictly to demonstrate web development capability. Using this app does not constitute a contract, commercial transaction, or partnership.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-slate-900 mb-2">3. Acceptable Use</h2>
              <p>
                Users are encouraged to interact with the resume parser, tab panels, and news sliders for testing purposes. However, please do not exploit endpoints or load spam payloads. Since the backend may connect to free-tier AI keys or local instances, any heavy automated testing might result in request limitations.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-slate-900 mb-2">4. Limitation of Liability</h2>
              <p>
                Under no circumstances shall the developer or creators be liable for any loss, server errors, or incorrect resume optimization advice. The score calculations are simulated or generated by local/external LLM calls and do not guarantee actual interview invitations or hiring success.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-slate-900 mb-2">5. Governing Scope</h2>
              <p>
                These terms are defined solely to communicate project scope to visitors, recruiters, and evaluators reviewing the portfolio. For inquiries regarding repository reuse, please contact the developer at <a href="mailto:yannambhargavi93@gmail.com" className="text-orange-600 hover:underline">yannambhargavi93@gmail.com</a>.
              </p>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
}
